language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
#  github_token: $GITHUB_TOKEN
  github_token: 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
 local_dir: dist
 on:
   branch: main